Use edx-api-doc-tools instead of deprecated django-swagger
edx/blockstore pull request #83
Opened 2020-09-15 15:24 UTC by morenol

## Description

This PR adds the changes to use edx-api-doc-tools instead of django-swagger

## Author Comments, Concerns, and Open Questions

As I mentioned in another PR, this [will only display](https://github.com/edx/api-doc-tools/issues/27) in  /api-docs/ the APIs that are in the /api/ path (it will not display the tagstore) APIs

## Test Instructions
Run the server and go to the /api-docs/, that should look like this:

![image](https://user-images.githubusercontent.com/22335041/93230556-c9488a80-f745-11ea-80ae-2ad2a21ac2a7.png)

## TODOs
If anything isn't yet done, list it here
- [ ] Squash before merging

2020-09-15 15:24 UTC, edx-webhook commented
Thanks for the pull request, @morenol! I've created [OSPR-4972](https://openedx.atlassian.net/browse/OSPR-4972) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.



<!-- comment:external_pr -->
<!-- jenkins ok to test -->

2020-09-15 15:26 UTC, morenol commented
Hi @symbolist, as you suggested in #68 I created this PR to move to edx-api-doc-tools

2020-09-17 02:14 UTC, natabene commented
@morenol Thank you for your contribution. Is this ready for our review?

2020-09-17 03:55 UTC, morenol commented
Hi @natabene. Yes, it is.

2020-09-17 14:11 UTC, natabene commented
@morenol Lining this up for our review.

2020-11-09 23:34 UTC, symbolist requested changes
@morenol Thanks! I tested this out and it is working as expected. Can you please resolve the conflicts and then I'll merge it.

2020-11-19 20:34 UTC, morenol commented
Hi @symbolist, Any updates on this?, or should we close this as a consequence of this https://github.com/edx/blockstore/pull/97/files?

2020-11-23 21:37 UTC, symbolist approved these changes
@morenol Thanks for resolving the conflicts! I don't get a notification when you last pushed. 

- [x] I tested this by viewing the docs in the devstack.
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation

2020-11-23 21:37 UTC, merged

2020-11-23 21:37 UTC, edx-webhook commented
@morenol 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/blockstore&entry.867055334=https://github.com/edx/blockstore/pull/83&entry.1484655318=https://github.com/morenol&entry.752974735=2020-09-15+15:24&entry.1917517419=2020-11-23+21:37&entry.2133058324=Yes) so we can improve your experience in the future.